### ISSUE TITLE
input-42-data.zip

### ISSUE THREAD

**Issue by wushaoxin123** [BKAUTO/ImageStitching-based-on-NISwGSP#1]
Hello, how can I get input-42- data.zip , link cannot be downloaded.

**Comment by BKAUTO** [comment]
Hello @wushaoxin123 ,

This project records my undergraduate thesis and is still under constructing. The present README file comes from the original [NISwGSP Project](https://github.com/nothinglo/NISwGSP) so I think the link may have been broken for some reason. If you still want the input data, I hold a copy on my local computer so you can leave me a email address.

**Comment by wushaoxin123** [comment]
Thank you very much. My email is 329010650@qq.com

**Comment by BKAUTO** [comment]
Done.
